name: deploy UriToS3Key code to dev 
on:
  push:
    paths:
      - 'src/UriToS3Key/**'
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          cd src/UriToS3Key 
          npm ci
        env:
          CI: true
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip output
        run: zip -qq -r function.zip .
        working-directory: src/UriToS3Key
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: qp-UriToS3KeyLambda
          zip_file: src/UriToS3Key/function.zip
